### ISSUE TITLE
Error in Get VM

### ISSUE THREAD

**Issue by ghost** [davejfranco/oci-action-api#1]
main.go: Extrae bien de la BD los datos con 
 //find vm in database
        vm := h.db.Get(name)
pero luego la busca en oci con  server, err := h.config.GetVM(vm)
Esta función en realidad busca en el compartment con resp, err := client.ListInstances(context.Background(), req) y retorna lo primero de la lista con server := VM{
                DisplayName:   *resp.Items[0].DisplayName,
                CompartmentID: *resp.Items[0].CompartmentId,
                OCID:          *resp.Items[0].Id,
Resultado:
Al buscar una máquina por nombre, retorna otra que no corresponde
Posibles soluciones:
1) el main.go que retorne lo encontrado en la BD y NO vaya a oci (no se me ocurre una razon para hacerlo, yo iba por esta, pero quería tu opinión)
2) corregir la funcion GetVM para que pusque por el instance ocid y no por compartment

**Comment by davejfranco** [comment]
Ya lo vi, realmente tengo que filtrar esa salida, te aviso cuando lo hay resuelto

**Comment by ghost** [comment]
Sólo tus comentarios, igual voy a hacer un Fork del proyecto

**Comment by davejfranco** [comment]
en el metodo agregue el nombre de la propia máquina para siempre devuelva o vacio o los datos de la maquina
req := core.ListInstancesRequest{CompartmentId: &vm.CompartmentID, DisplayName: &vm.DisplayName}
